// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createContent = `-- name: CreateContent :one
INSERT INTO content (id, memory_id, content_type, content, created_at, updated_at, content_url, metadata)
VALUES ($1, $2, $3, $4, NOW(), NOW(), $5, $6)
RETURNING id, memory_id, content_type, created_at, updated_at, content_url, content, metadata
`

type CreateContentParams struct {
	ID          uuid.UUID       `json:"id"`
	MemoryID    uuid.UUID       `json:"memory_id"`
	ContentType ContentType     `json:"content_type"`
	Content     string          `json:"content"`
	ContentUrl  sql.NullString  `json:"content_url"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, createContent,
		arg.ID,
		arg.MemoryID,
		arg.ContentType,
		arg.Content,
		arg.ContentUrl,
		arg.Metadata,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentUrl,
		&i.Content,
		&i.Metadata,
	)
	return i, err
}

const getContentByMemoryID = `-- name: GetContentByMemoryID :many
SELECT id, memory_id, content_type, created_at, updated_at, content_url, content, metadata FROM content WHERE memory_id = $1
`

func (q *Queries) GetContentByMemoryID(ctx context.Context, memoryID uuid.UUID) ([]Content, error) {
	rows, err := q.db.QueryContext(ctx, getContentByMemoryID, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.ContentType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentUrl,
			&i.Content,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
