// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memory (id, user_id, date, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, user_id, date, created_at, updated_at
`

type CreateMemoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, createMemory, arg.ID, arg.UserID, arg.Date)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemoryByUserID = `-- name: GetMemoryByUserID :one
SELECT id, user_id, date, created_at, updated_at FROM memory WHERE user_id = $1
`

func (q *Queries) GetMemoryByUserID(ctx context.Context, userID uuid.UUID) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemoryByUserID, userID)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemoryByUserIDAndDate = `-- name: GetMemoryByUserIDAndDate :one
SELECT id, user_id, date, created_at, updated_at FROM memory WHERE user_id = $1 AND date = $2
`

type GetMemoryByUserIDAndDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) GetMemoryByUserIDAndDate(ctx context.Context, arg GetMemoryByUserIDAndDateParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemoryByUserIDAndDate, arg.UserID, arg.Date)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
